"""Builds every message from content/advice.json. Code chooses lines; nothing here is generated by a model."""

from __future__ import annotations

import html
import json
from functools import lru_cache

from . import paths, rules

SEVERITY_LABEL = {
    "red": {"hi": "आज ही कदम उठाएं", "en": "Act today"},
    "amber": {"hi": "इस हफ़्ते कदम उठाएं", "en": "Act this week"},
    "yellow": {"hi": "निगरानी रखें", "en": "Monitor"},
    "review": {"hi": "जांच ज़रूरी", "en": "Needs review"},
}


@lru_cache(maxsize=1)
def library() -> dict:
    with open(paths.content_file("advice.json"), encoding="utf-8") as fh:
        return json.load(fh)


def entry(code: str) -> dict | None:
    return library()["parameters"].get(code)


def actions(code: str) -> list[str]:
    e = entry(code)
    return [line["action"] for line in e["do_now"]] if e else []


def lines(code: str, lang: str) -> list[str]:
    e = entry(code)
    return [line[lang] for line in e["do_now"]] if e else []


def name(code: str, lang: str) -> str:
    e = entry(code)
    return e["name"][lang] if e else code


def _fmt(value) -> str:
    if value is None:
        return "?"
    return f"{value:g}" if isinstance(value, (int, float)) else str(value)


def _date(iso: str | None) -> str:
    return iso[:10] if iso else "?"


def alert_text(case: dict, lang: str = "hi", page_url: str | None = None, data_as_of: str | None = None) -> str:
    """Telegram HTML message for the village relay."""
    code, esc = case["code"], html.escape
    place = f"{case['village']} ({case.get('block') or '-'}, {case.get('district') or '-'})"
    measured = f"{_fmt(case.get('value'))} {case.get('unit') or ''}".strip()
    limit = _fmt(case.get("acceptable_limit"))
    if lang == "hi":
        head = f"⚠️ <b>{esc(place)}</b>\nपानी की जांच में <b>{esc(name(code, 'hi'))}</b> मिला।"
        facts = f"मात्रा: {esc(measured)} (सीमा: {esc(limit)}) · लैब जांच: {_date(case.get('lab_approval'))}"
        todo = "अभी क्या करें:"
        tail = "जांच दोबारा पास होने तक यह सूचना लागू रहेगी।"
        asof = f"डेटा: JJM-WQMIS, {data_as_of}" if data_as_of else ""
        link = f"पूरी जानकारी: {page_url}" if page_url else ""
    else:
        head = f"⚠️ <b>{esc(place)}</b>\nThe water test found <b>{esc(name(code, 'en'))}</b>."
        facts = f"Measured: {esc(measured)} (limit: {esc(limit)}) · Lab test: {_date(case.get('lab_approval'))}"
        todo = "What to do now:"
        tail = "This alert stays until a re-test passes."
        asof = f"Data: JJM-WQMIS, as of {data_as_of}" if data_as_of else ""
        link = f"Details: {page_url}" if page_url else ""
    numbered = "\n".join(f"{i}. {esc(t)}" for i, t in enumerate(lines(code, lang), 1))
    parts = [head, facts, "", f"<b>{todo}</b>", numbered, "", tail, link, asof]
    return "\n".join(p for p in parts if p is not None).strip()


def voice_script(case: dict) -> str:
    """Short Hindi script for Polly (Kajal, hi-IN). Plain text, no symbols."""
    code = case["code"]
    say = [
        f"{case['village']} गाँव के लिए ज़रूरी सूचना।",
        f"पानी की जांच में {name(code, 'hi')} मिला है।",
        *lines(code, "hi"),
        "जांच दोबारा पास होने तक यह सूचना लागू रहेगी।",
    ]
    return " ".join(s.replace("·", ",") for s in say)


def engineer_card(case: dict, lang: str = "hi") -> str:
    code, esc = case["code"], html.escape
    e = entry(code)
    fix = e["engineer_fix"][lang] if e else ""
    sev = SEVERITY_LABEL.get(case.get("severity", "review"), SEVERITY_LABEL["review"])[lang]
    if lang == "hi":
        return (f"🛠 <b>{esc(case['village'])}</b> ({esc(case.get('block') or '-')})\n"
                f"{esc(name(code, 'hi'))}: {_fmt(case.get('value'))} {esc(case.get('unit') or '')} · {sev}\n"
                f"सुझाया गया काम: {esc(fix)}\nकाम करने के बाद नीचे बटन दबाएं।")
    return (f"🛠 <b>{esc(case['village'])}</b> ({esc(case.get('block') or '-')})\n"
            f"{esc(name(code, 'en'))}: {_fmt(case.get('value'))} {esc(case.get('unit') or '')} · {sev}\n"
            f"Suggested fix: {esc(fix)}\nTap a button after the work is done.")


def policy_context(code: str) -> dict:
    """What Cedar sees for a village message about this contaminant."""
    return {"contaminant_class": rules.contaminant_class(code), "actions": actions(code)}
